name: group_smskit
description: "A Flutter plugin to send SMS messages directly from Android and iOS devices using platform-specific native code."
version: 0.0.1
homepage: https://github.com/Pradipjadav05/group_smskit.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: sms_sender_plugin
    platforms:
      android:
        package: com.example.sms_sender
        pluginClass: SmsSenderPlugin
      ios:
        pluginClass: SmsSenderPlugin
      linux:
        pluginClass: SmsSenderPlugin
      macos:
        pluginClass: SmsSenderPlugin
      windows:
        pluginClass: SmsSenderPluginCApi
